spring.application.name=api-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/airtrack
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Warsaw
