spring.application.name=name=collector-seervice

openaq.apikey=${OPENAQ_API_KEY}
openaq.base-url=https://api.openaq.org/v3

collector.fetch-interval-ms=1800000
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.flyway.url=jdbc:postgresql://localhost:5432/airtrack
spring.flyway.user=
spring.flyway.password=

spring.flyway.enabled=false