spring.application.name=name=collector-seervice
openaq.apikey=d2b883102051595fc1f3549c72828f8aafd49800d7ed45f8d951e516255483ee

spring.flyway.url=jdbc:postgresql://localhost:5432/airtrack
spring.flyway.user=
spring.flyway.password=

spring.flyway.enabled=false